# Generated by Django 3.0.8 on 2020-07-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'get_latest_by': 'created', 'ordering': ['dandiset', '-version']},
        )
    ]
