# Generated by Django 3.0.8 on 2020-07-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_alter_version_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(name='asset', options={'ordering': ['version', 'path']})
    ]
