# Generated by Django 3.0.9 on 2020-08-07 22:01
import uuid

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import dandi.publish.models.asset
import dandi.publish.models.draft_asset


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_auto_20200722_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                (
                    'dandiset',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to='publish.Dandiset',
                    ),
                ),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=3000)),
                (
                    'metadata',
                    django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={'get_latest_by': 'created'},
        ),
        migrations.CreateModel(
            name='DraftAsset',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('path', models.CharField(max_length=512)),
                ('size', models.BigIntegerField()),
                (
                    'sha256',
                    models.CharField(
                        max_length=64,
                        validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')],
                    ),
                ),
                (
                    'metadata',
                    django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
                ),
                (
                    'blob',
                    models.FileField(
                        blank=True,
                        storage=dandi.publish.storage.create_s3_storage(
                            settings.DANDI_DANDISETS_BUCKET_NAME
                        ),
                        upload_to=dandi.publish.models.draft_asset._get_asset_blob_prefix,
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                (
                    'draft',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='assets',
                        to='publish.Draft',
                    ),
                ),
            ],
            options={'ordering': ['path']},
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['dandiset'], name='publish_dra_dandise_0e1eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='draftasset',
            index=models.Index(fields=['uuid'], name='publish_dra_uuid_5a5615_idx'),
        ),
        migrations.AddIndex(
            model_name='draftasset',
            index=models.Index(fields=['path'], name='publish_dra_path_c684e3_idx'),
        ),
    ]
