# Generated by Django 3.0.9 on 2020-08-10 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_auto_20200722_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftVersion',
            fields=[
                (
                    'dandiset',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to='publish.Dandiset',
                    ),
                ),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=3000)),
                (
                    'metadata',
                    django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={'get_latest_by': 'created'},
        ),
        migrations.AddIndex(
            model_name='draftversion',
            index=models.Index(fields=['dandiset'], name='publish_dra_dandise_07f636_idx'),
        ),
    ]
