# Generated by Django 3.0.9 on 2020-08-10 15:22

from django.db import migrations


def populate_drafts(apps, schema_editor):
    Dandiset = apps.get_model('publish', 'Dandiset')  # noqa: N806
    DraftVersion = apps.get_model('publish', 'DraftVersion')  # noqa: N806

    for dandiset in Dandiset.objects.all():
        try:
            dandiset.draft_version
        except DraftVersion.DoesNotExist:
            latest_version = dandiset.versions.order_by('-version').first()
            if latest_version:
                DraftVersion.objects.create(
                    dandiset=dandiset,
                    name=latest_version.name,
                    description=latest_version.description,
                    metadata=latest_version.metadata,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_add_drafts_model'),
    ]

    operations = [
        migrations.RunPython(populate_drafts, reverse_code=migrations.RunPython.noop),
    ]
