# Generated by Django 3.0.9 on 2020-08-23 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0007_deconstructable_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftversion',
            name='dandiset',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name='draft_version',
                serialize=False,
                to='publish.Dandiset',
            ),
        ),
    ]
