# Generated by Django 3.0.9 on 2020-09-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0010_timestampedmodel'),
        ('publish', '0009_remove_description'),
    ]

    operations = []
