# Generated by Django 4.1.1 on 2023-01-25 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('zarr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zarruploadfile',
            name='zarr_archive',
        ),
        migrations.DeleteModel(
            name='EmbargoedZarrUploadFile',
        ),
        migrations.DeleteModel(
            name='ZarrUploadFile',
        ),
    ]
