# Generated by Django 4.1.13 on 2023-11-11 04:25
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('zarr', '0001_initial_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embargoedzarrarchive',
            name='checksum',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='zarrarchive',
            name='checksum',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
