# Generated by Django 4.1.1 on 2022-12-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zarr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embargoedzarrarchive',
            name='file_count',
        ),
        migrations.RemoveField(
            model_name='embargoedzarrarchive',
            name='size',
        ),
        migrations.RemoveField(
            model_name='zarrarchive',
            name='file_count',
        ),
        migrations.RemoveField(
            model_name='zarrarchive',
            name='size',
        ),
    ]
