# Generated by Django 4.1.13 on 2024-08-16 18:02
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('zarr', '0003_alter_embargoedzarrarchive_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZarrArchiveVersion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('version', models.UUIDField()),
                (
                    'zarr',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='versions',
                        to='zarr.zarrarchive',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ZarrArchiveFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('key', models.CharField(db_index=True, max_length=256)),
                ('version_id', models.CharField(max_length=32)),
                ('etag', models.CharField(max_length=32)),
                ('zattrs', models.JSONField(null=True)),
                ('zarray', models.JSONField(null=True)),
                ('zgroup', models.JSONField(null=True)),
                (
                    'zarr_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='core_files',
                        to='zarr.zarrarchiveversion',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='zarrarchivefile',
            constraint=models.UniqueConstraint(
                fields=('key', 'version_id', 'etag'), name='unique-file-data'
            ),
        ),
        migrations.AddConstraint(
            model_name='zarrarchivefile',
            constraint=models.UniqueConstraint(
                fields=('zarr_version', 'key'), name='unique-zarr-key'
            ),
        ),
        migrations.AddConstraint(
            model_name='zarrarchivefile',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ('zarray__isnull', True),
                        ('zattrs__isnull', True),
                        ('zgroup__isnull', True),
                        models.Q(('key__endswith', '.zattrs'), _negated=True),
                        models.Q(('key__endswith', '.zarray'), _negated=True),
                        models.Q(('key__endswith', '.zgroup'), _negated=True),
                    ),
                    models.Q(
                        ('key__endswith', '.zattrs'),
                        ('zarray__isnull', True),
                        ('zattrs__isnull', False),
                        ('zgroup__isnull', True),
                    ),
                    models.Q(
                        ('key__endswith', '.zarray'),
                        ('zarray__isnull', False),
                        ('zattrs__isnull', True),
                        ('zgroup__isnull', True),
                    ),
                    models.Q(
                        ('key__endswith', '.zgroup'),
                        ('zarray__isnull', True),
                        ('zattrs__isnull', True),
                        ('zgroup__isnull', False),
                    ),
                    _connector='OR',
                ),
                name='consistent-metadata-field',
            ),
        ),
    ]
