# Generated by Django 4.1.1 on 2023-10-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('zarr', '0003_zarr_rename_tables_indexes_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='embargoedzarrarchive',
            name='zarr-embargoedzarrarchive-consistent-checksum-status',
        ),
        migrations.RemoveConstraint(
            model_name='zarrarchive',
            name='zarr-zarrarchive-consistent-checksum-status',
        ),
        migrations.AlterField(
            model_name='embargoedzarrarchive',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Uploaded', 'Uploaded'),
                    ('Ingesting', 'Ingesting'),
                    ('Complete', 'Complete'),
                ],
                default='Pending',
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name='zarrarchive',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Uploaded', 'Uploaded'),
                    ('Ingesting', 'Ingesting'),
                    ('Complete', 'Complete'),
                ],
                default='Pending',
                max_length=9,
            ),
        ),
        migrations.AddConstraint(
            model_name='embargoedzarrarchive',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ('checksum__isnull', True),
                        ('status__in', ['Pending', 'Uploaded', 'Ingesting']),
                    ),
                    models.Q(('checksum__isnull', False), ('status', 'Complete')),
                    _connector='OR',
                ),
                name='zarr-embargoedzarrarchive-consistent-checksum-status',
            ),
        ),
        migrations.AddConstraint(
            model_name='zarrarchive',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ('checksum__isnull', True),
                        ('status__in', ['Pending', 'Uploaded', 'Ingesting']),
                    ),
                    models.Q(('checksum__isnull', False), ('status', 'Complete')),
                    _connector='OR',
                ),
                name='zarr-zarrarchive-consistent-checksum-status',
            ),
        ),
    ]
