# Generated by Django 4.1.13 on 2024-08-21 16:06
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('zarr', '0003_alter_embargoedzarrarchive_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zarrarchive',
            name='embargoed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='EmbargoedZarrArchive',
        ),
    ]
