# Generated by Django 4.1.13 on 2023-11-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('zarr', '0003_zarr_rename_tables_indexes_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embargoedzarrarchive',
            name='checksum',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='zarrarchive',
            name='checksum',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
