# Generated by Django 4.1.13 on 2024-08-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarr', '0004_zarrarchiveversion_zarrarchivefile_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='zarrarchivefile',
            name='unique-zarr-key',
        ),
        migrations.AddConstraint(
            model_name='zarrarchivefile',
            constraint=models.UniqueConstraint(fields=('zarr_version', 'key', 'version_id'), name='unique-zarr-key-version'),
        ),
    ]
