# Generated by Django 4.1.13 on 2023-11-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'zarr',
            '0004_remove_embargoedzarrarchive_zarr-embargoedzarrarchive-'
            'consistent-checksum-status_and_more',
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='embargoedzarrarchive',
            name='zarr-embargoedzarrarchive-consistent-checksum-status',
        ),
        migrations.RemoveConstraint(
            model_name='zarrarchive',
            name='zarr-zarrarchive-consistent-checksum-status',
        ),
        migrations.AlterField(
            model_name='embargoedzarrarchive',
            name='checksum',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zarrarchive',
            name='checksum',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='embargoedzarrarchive',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ('checksum', ''), ('status__in', ['Pending', 'Uploaded', 'Ingesting'])
                    ),
                    models.Q(models.Q(('checksum', ''), _negated=True), ('status', 'Complete')),
                    _connector='OR',
                ),
                name='zarr-embargoedzarrarchive-consistent-checksum-status',
            ),
        ),
        migrations.AddConstraint(
            model_name='zarrarchive',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ('checksum', ''), ('status__in', ['Pending', 'Uploaded', 'Ingesting'])
                    ),
                    models.Q(models.Q(('checksum', ''), _negated=True), ('status', 'Complete')),
                    _connector='OR',
                ),
                name='zarr-zarrarchive-consistent-checksum-status',
            ),
        ),
    ]
