# Generated by Django 5.2.7 on 2026-02-10 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarr', '0005_remove_zarrarchive_embargoed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZarrArchiveVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.UUIDField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('zarr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zarr.zarrarchive')),
            ],
        ),
        migrations.CreateModel(
            name='ZarrArchiveChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=256)),
                ('object_version_id', models.CharField(max_length=32)),
                ('etag', models.CharField(max_length=32)),
                ('delete_marker', models.BooleanField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zarr.zarrarchiveversion')),
            ],
        ),
    ]
