# Generated by Django 4.1.13 on 2024-08-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarr', '0005_remove_zarrarchivefile_unique-zarr-key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='zarrarchivefile',
            name='unique-zarr-key-version',
        ),
        migrations.AddConstraint(
            model_name='zarrarchivefile',
            constraint=models.UniqueConstraint(fields=('zarr_version', 'key'), name='unique-zarr-key'),
        ),
    ]
