# Generated by Django 5.2.13 on 2026-08-11 15:52

from __future__ import annotations

import uuid

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('zarr', '0006_zarrarchive_upload_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZarrUpload',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('blob', models.FileField(blank=True, upload_to='')),
                ('upload_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                (
                    'etag',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=40,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator('^[0-9a-f]{32}-\\d{1,5}$')
                        ],
                    ),
                ),
                (
                    'multipart_upload_id',
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ('size', models.PositiveBigIntegerField()),
                ('chunk_key', models.CharField(max_length=1024)),
                (
                    'zarr',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='uploads',
                        to='zarr.zarrarchive',
                    ),
                ),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
                'indexes': [models.Index(fields=['etag'], name='zarr_zarrup_etag_508798_idx')],
            },
        ),
    ]
