_commit: v0.44.0
_src_path: gh:kitware-resonant/cookiecutter-resonant
core_app_name: api
include_example_code: false
project_name: DANDI Archive
project_slug: dandiapi
python_package_name: dandiapi
site_domain: api.dandiarchive.org
use_asgi: false
