# Generated by Django 4.1.13 on 2024-02-23 00:16
from __future__ import annotations

from django.db import migrations, models


def remove_embargoed_objects(apps, _):
    ProcessedS3Log = apps.get_model('analytics.ProcessedS3Log')
    ProcessedS3Log.objects.filter(embargoed=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0001_initial_v2'),
    ]

    operations = [
        migrations.RunPython(remove_embargoed_objects),
        migrations.RemoveConstraint(
            model_name='processeds3log',
            name='analytics_processeds3log_unique_name_embargoed',
        ),
        migrations.RemoveField(
            model_name='processeds3log',
            name='embargoed',
        ),
        migrations.AddConstraint(
            model_name='processeds3log',
            constraint=models.UniqueConstraint(
                fields=('name',), name='analytics_processeds3log_unique_name'
            ),
        ),
    ]
