# Generated by Django 4.1.4 on 2023-05-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processeds3log',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='processeds3log',
            constraint=models.UniqueConstraint(
                fields=('name', 'embargoed'), name='analytics_processeds3log_unique_name_embargoed'
            ),
        ),
    ]
