# Generated by Django 4.2.23 on 2025-07-02 14:20
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'analytics',
            '0002_remove_processeds3log_analytics_processeds3log_unique_name_embargoed_and_more',
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedS3Log',
        ),
    ]
