#!/bin/bash
export AWS_CONFIG_FILE="/home/ubuntu/.aws/config"
set -e

BACKUP_PATH="$HOME/backups/"
BACKUP_NAME="mongo-backup-$(date +%Y%m%dT%H%M%S)"

# backup all databases
/usr/bin/mongodump --gzip --out "$BACKUP_PATH/$BACKUP_NAME"

# upload backup to s3
/usr/bin/aws s3 cp "$BACKUP_PATH/$BACKUP_NAME" "s3://dandiarchive/mongo-backup/$BACKUP_NAME" --recursive

# remove backups locally
rm -rf "$BACKUP_PATH/$BACKUP_NAME"
