# Generated by Django 3.0.9 on 2020-11-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={},
        ),
        migrations.AlterModelOptions(
            name='versionmetadata',
            options={},
        ),
    ]
