# Generated by Django 3.1.7 on 2021-03-23 13:51

from django.db import migrations, models
import uuid

from django.db.migrations.operations.fields import RenameField


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_unique_asset_blob_etag_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='upload_id',
            new_name='multipart_upload_id',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='uuid',
            new_name='upload_id',
        ),
    ]
