# Generated by Django 3.1.7 on 2021-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_rename_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='multipart_upload_id',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
