# Generated by Django 3.0.9 on 2020-11-19 16:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_validation_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='assetblob',
            options={},
        ),
        migrations.RemoveField(
            model_name='assetblob',
            name='path',
        ),
        migrations.RemoveField(
            model_name='assetblob',
            name='uuid',
        ),
        migrations.AddField(
            model_name='asset',
            name='path',
            field=models.CharField(default='DEFAULT_PATH', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='assetmetadata',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('path', 'version')},
        ),
        migrations.AddIndex(
            model_name='assetblob',
            index=models.Index(fields=['sha256'], name='api_assetbl_sha256_828fb9_idx'),
        ),
    ]
