# Generated by Django 3.0.9 on 2020-11-12 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_validation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='sha256',
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')],
            ),
        ),
    ]
