# Generated by Django 3.1.7 on 2021-03-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_generic_multipart_upload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='doi',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
