# Generated by Django 4.1.13 on 2023-11-11 04:25
from __future__ import annotations

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetblob',
            name='sha256',
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')],
            ),
        ),
        migrations.AlterField(
            model_name='embargoedassetblob',
            name='sha256',
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')],
            ),
        ),
        migrations.AlterField(
            model_name='embargoedupload',
            name='etag',
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=40,
                null=True,
                validators=[django.core.validators.RegexValidator('^[0-9a-f]{32}(-[1-9][0-9]*)?$')],
            ),
        ),
        migrations.AlterField(
            model_name='upload',
            name='etag',
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=40,
                null=True,
                validators=[django.core.validators.RegexValidator('^[0-9a-f]{32}(-[1-9][0-9]*)?$')],
            ),
        ),
        migrations.AlterField(
            model_name='version',
            name='doi',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
