# Generated by Django 3.0.9 on 2021-02-09 15:45

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_default_oauth_application'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assetblob',
            name='api_assetbl_sha256_828fb9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='versionmetadata',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='assetblob',
            index=django.contrib.postgres.indexes.HashIndex(
                fields=['sha256'], name='api_assetbl_sha256_79e05b_hash'
            ),
        ),
        migrations.AddIndex(
            model_name='versionmetadata',
            index=django.contrib.postgres.indexes.HashIndex(
                fields=['metadata'], name='api_version_metadat_1146a6_hash'
            ),
        ),
        migrations.AddIndex(
            model_name='versionmetadata',
            index=django.contrib.postgres.indexes.HashIndex(
                fields=['name'], name='api_version_name_ed2a83_hash'
            ),
        ),
    ]
