# Generated by Django 4.1.13 on 2024-03-27 18:45
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_asset_path_collation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['version']},
        ),
    ]
