# Generated by Django 3.2 on 2021-05-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_default_oauth_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', '-'),
                    ('VALIDATING', 'Validating'),
                    ('VALID', 'Valid'),
                    ('INVALID', 'Invalid'),
                ],
                default='PENDING',
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name='asset',
            name='validation_error',
            field=models.TextField(default=''),
        ),
    ]
