# Generated by Django 3.2 on 2021-05-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_validation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Validating', 'Validating'),
                    ('Valid', 'Valid'),
                    ('Invalid', 'Invalid'),
                ],
                default='Pending',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='version',
            name='validation_error',
            field=models.TextField(default=''),
        ),
    ]
