# Generated by Django 3.2 on 2021-05-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_version_validation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
