# Generated by Django 3.0.9 on 2020-08-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_draft_version_related_name'),
    ]

    operations = [
        migrations.RemoveField(model_name='draftversion', name='description'),
        migrations.RemoveField(model_name='version', name='description'),
    ]
