# Generated by Django 4.1.13 on 2024-07-24 01:30
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_remove_embargoedassetblob_dandiset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dandiset_id', models.IntegerField()),
                ('username', models.CharField(max_length=39)),
                ('user_email', models.CharField(max_length=254)),
                ('user_fullname', models.CharField(max_length=301)),
                (
                    'record_type',
                    models.CharField(
                        choices=[
                            ('create_dandiset', 'create_dandiset'),
                            ('change_owners', 'change_owners'),
                            ('update_metadata', 'update_metadata'),
                            ('add_asset', 'add_asset'),
                            ('update_asset', 'update_asset'),
                            ('remove_asset', 'remove_asset'),
                            ('create_zarr', 'create_zarr'),
                            ('upload_zarr_chunks', 'upload_zarr_chunks'),
                            ('delete_zarr_chunks', 'delete_zarr_chunks'),
                            ('finalize_zarr', 'finalize_zarr'),
                            ('unembargo_dandiset', 'unembargo_dandiset'),
                            ('publish_dandiset', 'publish_dandiset'),
                            ('delete_dandiset', 'delete_dandiset'),
                        ],
                        max_length=32,
                    ),
                ),
                ('details', models.JSONField(blank=True)),
            ],
        ),
    ]
