# Generated by Django 4.1.13 on 2024-07-01 21:16
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_remove_embargoedassetblob_dandiset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dandiset',
            name='embargo_status',
            field=models.CharField(
                choices=[
                    ('EMBARGOED', 'Embargoed'),
                    ('UNEMBARGO_PENDING', 'Unembargo Pending'),
                    ('UNEMBARGOING', 'Unembargoing'),
                    ('OPEN', 'Open'),
                ],
                default='OPEN',
                max_length=17,
            ),
        ),
    ]
