# Generated by Django 4.1.13 on 2024-08-20 15:14
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_auditrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='previous',
        ),
    ]
