# Generated by Django 4.1.13 on 2024-09-09 17:25
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_auditrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageCollectionEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('records', models.JSONField()),
            ],
        ),
    ]
