# Generated by Django 3.2.4 on 2021-06-23 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_asset_published'),
        ('api', '0010_application'),
    ]

    operations = [
    ]
