# Generated by Django 3.2.4 on 2021-06-30 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_blank_validation_errors'),
        ('api', '0011_stagingapplication'),
    ]

    operations = []
