# Generated by Django 4.1.13 on 2024-10-23 15:52
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_asset_access_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='previous',
        ),
    ]
