# Generated by Django 4.2.17 on 2024-12-09 19:32
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0012_remove_asset_previous'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetpath',
            name='consistent-slash',
        ),
        migrations.AddConstraint(
            model_name='assetpath',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('path__endswith', '/'),
                    ('path__startswith', '/'),
                    _connector='OR',
                    _negated=True,
                ),
                name='consistent-slash',
            ),
        ),
    ]
