# Generated by Django 3.2 on 2021-07-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0012_merge_20210630_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Validating', 'Validating'),
                    ('Valid', 'Valid'),
                    ('Invalid', 'Invalid'),
                    ('Published', 'Published'),
                ],
                default='Pending',
                max_length=10,
            ),
        ),
    ]
