# Generated by Django 4.2.17 on 2024-12-11 17:17
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_remove_assetpath_consistent_slash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageCollectionEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                (
                    'type',
                    models.CharField(
                        help_text='The model name of the records that were garbage collected.',
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='GarbageCollectionEventRecord',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'record',
                    models.JSONField(
                        help_text='JSON serialization of the record that was garbage collected.'
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='records',
                        to='api.garbagecollectionevent',
                    ),
                ),
            ],
        ),
    ]
