# Generated by Django 4.2.17 on 2024-12-11 17:12
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_remove_assetpath_consistent_slash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageCollectionEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'type',
                    models.CharField(
                        help_text='The model name of the records that were garbage collected.',
                        max_length=255,
                    ),
                ),
                (
                    'records',
                    models.JSONField(
                        help_text='JSON serialization of the queryset of records that were garbage collected.'
                    ),
                ),
                (
                    'garbage_collection_event_id',
                    models.UUIDField(
                        editable=False,
                        help_text='Unique identifier for the garbage collection event.'
                        ' Used to associate multiple records that are part of the same GC event.',
                    ),
                ),
            ],
        ),
    ]
