# Generated by Django 3.2.5 on 2021-07-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_add_published_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagingapplication',
            name='skip_authorization',
            field=models.BooleanField(default=True),
        ),
    ]
