# Generated by Django 4.2.17 on 2025-01-17 17:45
from __future__ import annotations

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0014_garbagecollectionevent_garbagecollectioneventrecord'),
    ]

    operations = [
        UnaccentExtension(),
    ]
