# Generated by Django 4.2.17 on 2025-01-03 21:10
from __future__ import annotations

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_unaccent_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='DandisetStar',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'dandiset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='stars',
                        to='api.dandiset',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='starred_dandisets',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='dandisetstar',
            constraint=models.UniqueConstraint(
                fields=('user', 'dandiset'), name='unique-user-dandiset-star'
            ),
        ),
    ]
