# Generated by Django 3.2 on 2021-08-09 18:00

import django.contrib.postgres.indexes
from django.db import migrations, models


def migrate_metadata(apps, schema_editor):
    Version = apps.get_model('api', 'Version')
    VersionMetadata = apps.get_model('api', 'VersionMetadata')
    Asset = apps.get_model('api', 'Asset')
    AssetMetadata = apps.get_model('api', 'AssetMetadata')

    moved_metadata = VersionMetadata.objects.filter(id=models.OuterRef('old_metadata')).values_list(
        'metadata'
    )[:1]
    moved_name = VersionMetadata.objects.filter(id=models.OuterRef('old_metadata')).values_list(
        'name'
    )[:1]
    Version.objects.update(
        metadata=models.Subquery(moved_metadata), name=models.Subquery(moved_name)
    )

    moved_metadata = AssetMetadata.objects.filter(id=models.OuterRef('old_metadata')).values_list(
        'metadata'
    )[:1]
    Asset.objects.update(metadata=models.Subquery(moved_metadata))


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0015_validation_fields'),
    ]

    operations = [
        # Move the original metadata fields to old_metadata
        migrations.RenameField(
            model_name='asset',
            old_name='metadata',
            new_name='old_metadata',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='metadata',
            new_name='old_metadata',
        ),
        # Create metadata field on Asset
        migrations.AddField(
            model_name='asset',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        # Create name and metadata fields on Version
        migrations.AddField(
            model_name='version',
            name='name',
            field=models.CharField(default='temporary_name', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='version',
            index=django.contrib.postgres.indexes.HashIndex(
                fields=['metadata'], name='api_version_metadat_f0b8f8_hash'
            ),
        ),
        migrations.AddIndex(
            model_name='version',
            index=django.contrib.postgres.indexes.HashIndex(
                fields=['name'], name='api_version_name_5d8af6_hash'
            ),
        ),
        # Move the data from the old_metadata fields to the new metadata fields
        migrations.RunPython(migrate_metadata),
        # Delete the old_metadata fields
        migrations.RemoveField(
            model_name='Asset',
            name='old_metadata',
        ),
        migrations.RemoveField(
            model_name='Version',
            name='old_metadata',
        ),
        migrations.DeleteModel(
            name='AssetMetadata',
        ),
        migrations.DeleteModel(
            name='VersionMetadata',
        ),
    ]
