# Generated by Django 4.2.19 on 2025-02-20 22:32
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0016_dandisetstar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpath',
            name='path',
            field=models.CharField(db_collation='C', max_length=512),
        ),
    ]
