# Generated by Django 3.2 on 2021-08-27 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0016_remove_metadata_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.CharField(
                max_length=13,
                validators=[django.core.validators.RegexValidator('^(0\\.\\d{6}\\.\\d{4})|draft$')],
            ),
        ),
    ]
