# Generated by Django 4.2.19 on 2025-04-08 21:48
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0017_assetpath_path_collation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dandiset',
            options={
                'default_permissions': [],
                'ordering': ['id'],
                'permissions': [
                    ('create_dandiset', 'Can create the dandiset'),
                    ('view_dandiset', 'Can view the dandiset'),
                    ('update_dandiset', 'Can update the dandiset'),
                    ('delete_dandiset', 'Can delete the dandiset'),
                    ('manage_dandiset_uploads', 'Can manage the dandiset uploads'),
                    ('publish_dandiset', 'Can publish the dandiset'),
                    ('unembargo_dandiset', 'Can unembargo the dandiset'),
                    ('star_dandiset', 'Can star the dandiset'),
                    ('view_dandiset_roles', 'Can view the dandiset roles'),
                    ('update_dandiset_roles', 'Can update the dandiset roles'),
                    ('view_dandiset_versions', 'Can view the dandiset versions'),
                    ('create_dandiset_assets', 'Can create the dandiset assets'),
                    ('view_dandiset_assets', 'Can view the dandiset assets'),
                    ('delete_dandiset_assets', 'Can delete the dandiset assets'),
                    ('update_dandiset_assets', 'Can update the dandiset assets'),
                    ('view_zarr_archive', 'Can view the zarr archive'),
                    ('create_zarr_archive', 'Can create the zarr archive'),
                    ('delete_zarr_archive', 'Can delete the zarr archive'),
                    ('finalize_zarr_archive', 'Can finalize the zarr archive'),
                    ('create_zarr_archive_files', 'Can create the zarr archive files'),
                    ('delete_zarr_archive_files', 'Can delete the zarr archive files'),
                    ('list_zarr_archive_files', 'Can list the zarr archive files'),
                ],
            },
        ),
        migrations.CreateModel(
            name='DandisetRole',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('rolename', models.CharField(max_length=150)),
                (
                    'dandiset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='roles',
                        to='api.dandiset',
                    ),
                ),
                (
                    'group',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='dandisetrole',
                        to='auth.group',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='DandisetRole',
            constraint=models.UniqueConstraint(
                fields=('dandiset', 'rolename'), name='unique-dandiset-rolename'
            ),
        ),
    ]
