# Generated by Django 4.2.19 on 2025-03-21 17:06
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0017_assetpath_path_collation'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecord',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddConstraint(
            model_name='auditrecord',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('admin', False), ('description', '')),
                    models.Q(('admin', True), models.Q(('description', ''), _negated=True)),
                    _connector='OR',
                ),
                name='admin-description-pairing',
            ),
        ),
    ]
