# Generated by Django 3.2.4 on 2021-09-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0017_alter_version_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
