# Generated by Django 3.2.4 on 2021-10-21 21:03

from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
import django.db.models.deletion
import django_extensions.db.fields

from dandiapi.api.models import UserMetadata


def update_existing_users(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    """Automatically approve any existing users."""
    for user in User.objects.all():
        if user.is_active:
            status = UserMetadata.Status.APPROVED
        else:
            status = UserMetadata.Status.REJECTED
        UserMetadata.objects.create(user=user, status=status)


def reverse_update_existing_users(app, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_alter_validation_errors'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetadata',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('INCOMPLETE', 'Incomplete'),
                            ('PENDING', 'Pending'),
                            ('APPROVED', 'Approved'),
                            ('REJECTED', 'Rejected'),
                        ],
                        default='INCOMPLETE',
                        max_length=10,
                    ),
                ),
                ('questionnaire_form', models.JSONField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='', max_length=1000)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='metadata',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RunPython(update_existing_users, reverse_update_existing_users),
    ]
