# Generated by Django 4.2.20 on 2025-04-08 20:20

from __future__ import annotations

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0018_auditrecord_admin_auditrecord_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='institutional_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='verification_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
