# Generated by Django 4.2.20 on 2025-04-15 19:19
from __future__ import annotations

import django.contrib.postgres.indexes
from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0020_alter_upload_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper('path'), name='gin_trgm_ops'
                ),
                name='api_asset_path_gin',
            ),
        ),
    ]
