# Generated by Django 4.2.19 on 2025-04-16 17:55
from __future__ import annotations

from django.db import migrations, models
import oauth2_provider.generators
import oauth2_provider.models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0020_alter_upload_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagingapplication',
            name='allowed_origins',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Allowed origins list to enable CORS, space separated',
            ),
        ),
        migrations.AddField(
            model_name='stagingapplication',
            name='hash_client_secret',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stagingapplication',
            name='post_logout_redirect_uris',
            field=models.TextField(
                blank=True, default='', help_text='Allowed Post Logout URIs list, space separated'
            ),
        ),
        migrations.AlterField(
            model_name='stagingapplication',
            name='client_secret',
            field=oauth2_provider.models.ClientSecretField(
                blank=True,
                db_index=True,
                default=oauth2_provider.generators.generate_client_secret,
                help_text='Hashed on Save. Copy it now if this is a new secret.',
                max_length=255,
            ),
        ),
    ]
