# Generated by Django 4.2.23 on 2025-07-02 14:42
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0021_stagingapplication_allowed_origins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetblob',
            name='download_count',
        ),
    ]
