# Generated by Django 4.2.20 on 2025-04-28 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0021_stagingapplication_allowed_origins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='last_asset_add_remove_time',
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 28, 17, 14, 30, 849790, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='last_summary_time',
            field=models.DateTimeField(
                # Notably, last_summary_time must be before last_asset_add_remove_time
                default=datetime.datetime(
                    2025, 4, 28, 17, 14, 4, 34617, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
