# Generated by Django 4.2.23 on 2025-07-09 18:24
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0021_stagingapplication_allowed_origins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStats',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, unique=True)),
                ('dandiset_count', models.PositiveIntegerField()),
                ('published_dandiset_count', models.PositiveIntegerField()),
                ('user_count', models.PositiveIntegerField()),
                ('size', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Application Stats',
            },
        ),
    ]
