# Generated by Django 4.2.19 on 2025-04-18 21:19
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('oauth2_provider', '0012_add_token_checksum'),
        ('api', '0021_stagingapplication_allowed_origins_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StagingApplication',
        ),
        migrations.CreateModel(
            name='StagingApplication',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oauth2_provider.application',),
        ),
    ]
