# Generated by Django 4.0 on 2022-01-19 14:54

import uuid

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields

import dandiapi.api.storage


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0022_upload_dandiset_alter_stagingapplication_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbargoedZarrArchive',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('zarr_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('file_count', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                (
                    'dandiset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='embargoed_zarr_archives',
                        to='api.dandiset',
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='EmbargoedZarrUploadFile',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('path', models.CharField(max_length=512)),
                (
                    'etag',
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator('^[0-9a-f]{32}(-[1-9][0-9]*)?$')
                        ],
                    ),
                ),
                (
                    'blob',
                    models.FileField(
                        blank=True, storage=dandiapi.api.storage.get_embargo_storage, upload_to=''
                    ),
                ),
                (
                    'zarr_archive',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='active_uploads',
                        to='api.embargoedzarrarchive',
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
            },
        ),
    ]
