# Generated by Django 4.2.23 on 2025-08-11 17:13
from __future__ import annotations

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0023_applicationstats'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetblob',
            name='unique-etag-size',
        ),
        migrations.AlterField(
            model_name='assetblob',
            name='etag',
            field=models.CharField(
                max_length=40,
                unique=True,
                validators=[django.core.validators.RegexValidator('^[0-9a-f]{32}(-[1-9][0-9]*)?$')],
            ),
        ),
    ]
