# Generated by Django 4.0 on 2022-02-15 14:41

from django.db import migrations, models
import django.db.models.deletion


def set_default_zarrarchive_dandiset(apps, schema_editor):
    """Set the dandiset field for all existing uploads to the first dandiset."""
    Dandiset = apps.get_model('api', 'Dandiset')
    ZarrArchive = apps.get_model('api', 'ZarrArchive')
    # noqa: E501 Fresh installations will have no dandisets, but also no zarr_archives, so initialize this inside the loop
    first_dandiset = None
    zarr_archives = list(ZarrArchive.objects.filter(dandiset=None).all())
    for zarr_archive in zarr_archives:
        if first_dandiset is None:
            first_dandiset = Dandiset.objects.order_by('created').first()
        zarr_archive.dandiset = first_dandiset
    ZarrArchive.objects.bulk_update(zarr_archives, ['dandiset'])


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0024_biginteger_zarrarchives'),
    ]

    operations = [
        migrations.AddField(
            model_name='zarrarchive',
            name='dandiset',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='zarr_archives',
                to='api.dandiset',
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_zarrarchive_dandiset),
        migrations.AlterField(
            model_name='zarrarchive',
            name='dandiset',
            field=models.ForeignKey(
                # This will never be used
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='zarr_archives',
                to='api.dandiset',
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='embargoedzarrarchive',
            constraint=models.UniqueConstraint(
                fields=('dandiset', 'name'), name='unique-embargo-dandiset-name'
            ),
        ),
        migrations.AddConstraint(
            model_name='zarrarchive',
            constraint=models.UniqueConstraint(
                fields=('dandiset', 'name'), name='unique-dandiset-name'
            ),
        ),
    ]
