# Generated by Django 4.2.23 on 2025-08-04 21:24
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0024_remove_assetblob_unique_etag_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
