# Generated by Django 4.2.23 on 2025-09-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auditrecord_timestamp_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataciteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('CREATE_DOI', 'Create DOI'), ('UPDATE_DOI', 'Update DOI'), ('HIDE_DOI', 'Hide DOI'), ('DELETE_DOI', 'Delete DOI')], max_length=10)),
                ('dandiset_identifier', models.PositiveIntegerField()),
                ('dandiset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datacite_events', to='api.dandiset')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='dataciteevent',
            constraint=models.CheckConstraint(check=models.Q(('dandiset__isnull', True), ('dandiset_id', models.F('dandiset_identifier')), _connector='OR'), name='dandiset_fields_equal'),
        ),
    ]
