# Generated by Django 5.2.6 on 2025-09-26 10:55
from __future__ import annotations

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0025_auditrecord_timestamp_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetblob',
            name='etag',
            field=models.CharField(
                max_length=40,
                unique=True,
                validators=[django.core.validators.RegexValidator('^[0-9a-f]{32}-\\d{1,5}$')],
            ),
        ),
        migrations.AlterField(
            model_name='upload',
            name='etag',
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=40,
                null=True,
                validators=[django.core.validators.RegexValidator('^[0-9a-f]{32}-\\d{1,5}$')],
            ),
        ),
    ]
