# Generated by Django 4.0.3 on 2022-03-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0026_alter_asset_id_alter_assetblob_id_alter_dandiset_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embargoedzarrarchive',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Ingesting', 'Ingesting'),
                    ('Complete', 'Complete'),
                ],
                default='Pending',
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name='zarrarchive',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Ingesting', 'Ingesting'),
                    ('Complete', 'Complete'),
                ],
                default='Pending',
                max_length=9,
            ),
        ),
    ]
