# Generated by Django 4.0.3 on 2022-04-06 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0027_embargoedzarrarchive_status_zarrarchive_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='previous',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='api.asset',
            ),
        ),
    ]
