# Generated by Django 4.0.3 on 2022-04-20 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0028_alter_asset_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetadata',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='metadata',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
