# Generated by Django 5.2.7 on 2026-01-12 21:55
from __future__ import annotations

from django.db import migrations, models

import dandiapi.api.models.asset


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0029_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='path',
            field=models.CharField(
                db_collation='C',
                db_index=True,
                max_length=512,
                validators=[dandiapi.api.models.asset.validate_asset_path],
            ),
        ),
    ]
