# Generated by Django 5.2.7 on 2025-11-14 20:26
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0029_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='release_notes',
            field=models.CharField(
                blank=True,
                default='',
                help_text='The most recent release notes used for publishing.',
                max_length=512,
            ),
        ),
    ]
