# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0029_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text='Unique identifier for the template (e.g., "publish_reminder")', max_length=255, unique=True)),
                ('subject_template', models.CharField(help_text='Subject line template pattern (for documentation purposes).', max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Description of when this template is used.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('template_name', models.CharField(blank=True, default='', help_text='Name of the template used (preserved if template is deleted).', max_length=255)),
                ('subject', models.CharField(help_text='The actual subject line sent.', max_length=500)),
                ('to', models.JSONField(default=list, help_text='List of recipient email addresses.')),
                ('cc', models.JSONField(blank=True, default=list, help_text='List of CC recipient email addresses.')),
                ('bcc', models.JSONField(blank=True, default=list, help_text='List of BCC recipient email addresses.')),
                ('reply_to', models.JSONField(blank=True, default=list, help_text='List of reply-to email addresses.')),
                ('text_content', models.TextField(help_text='Plain text version of the email.')),
                ('html_content', models.TextField(blank=True, default='', help_text='HTML version of the email.')),
                ('render_context', models.JSONField(blank=True, default=dict, help_text='The context variables used to render the template.')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the email was sent.')),
                ('dandiset', models.ForeignKey(blank=True, help_text='The dandiset this email relates to (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='api.dandiset')),
                ('template', models.ForeignKey(blank=True, help_text='The template used to generate this email.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='api.emailtemplate')),
                ('recipients', models.ManyToManyField(blank=True, help_text='User objects who received this email.', related_name='received_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sentemail',
            index=models.Index(fields=['template_name'], name='api_sentema_templat_2c5c85_idx'),
        ),
        migrations.AddIndex(
            model_name='sentemail',
            index=models.Index(fields=['sent_at'], name='api_sentema_sent_at_0d3dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='sentemail',
            index=models.Index(fields=['dandiset'], name='api_sentema_dandise_b5017e_idx'),
        ),
    ]
