# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0029_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='dandiset',
            name='publish_reminder_sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
