# Generated by Django

from django.db import migrations


def populate_email_templates(apps, schema_editor):
    """Create EmailTemplate records for all email types used in the system.

    Note: The actual template content is stored in filesystem at
    dandiapi/api/templates/api/mail/. This migration just creates metadata records.
    """
    EmailTemplate = apps.get_model('api', 'EmailTemplate')

    templates = [
        {
            'name': 'publish_reminder',
            'subject_template': 'Reminder: Publish your Dandiset "{{ dandiset.name }}"',
            'description': 'Sent to dandiset owners whose draft-only dandisets have been inactive for 30+ days, reminding them to publish. Template file: publish_reminder.html',
        },
        {
            'name': 'ownership_added',
            'subject_template': 'Added to Dandiset "{{ dandiset_name }}"',
            'description': 'Sent when a user is added as an owner of a dandiset. Template file: added_message.txt',
        },
        {
            'name': 'ownership_removed',
            'subject_template': 'Removed from Dandiset "{{ dandiset_name }}"',
            'description': 'Sent when a user is removed as an owner from a dandiset. Template file: removed_message.txt',
        },
        {
            'name': 'registered_notice',
            'subject_template': 'DANDI: New user registered: {{ user_email }}',
            'description': 'Sent to the admin list and user when a new user registers. Template file: registered_message.txt',
        },
        {
            'name': 'new_user_review',
            'subject_template': 'DANDI: Review new user: {{ username }}',
            'description': 'Sent to admins when a new user needs to be reviewed/approved. Template file: new_user_message.txt',
        },
        {
            'name': 'user_approved',
            'subject_template': 'Your DANDI Account',
            'description': 'Sent to a user when their account is approved. Template file: approved_user_message.txt',
        },
        {
            'name': 'user_rejected',
            'subject_template': 'Your DANDI Account',
            'description': 'Sent to a user when their account is rejected. Template file: rejected_user_message.txt',
        },
        {
            'name': 'pending_users_review',
            'subject_template': 'DANDI: new user registrations to review',
            'description': 'Periodic email to admins listing users awaiting approval. Template file: pending_users_message.txt',
        },
        {
            'name': 'dandiset_unembargoed',
            'subject_template': 'Your Dandiset has been unembargoed!',
            'description': 'Sent to dandiset owners when their dandiset is successfully unembargoed. Template file: dandiset_unembargoed.html',
        },
        {
            'name': 'dandiset_unembargo_failed',
            'subject_template': 'DANDI: Unembargo failed for dandiset {{ dandiset.identifier }}',
            'description': 'Sent to dandiset owners and devs when unembargo fails. Template file: dandiset_unembargo_failed.html',
        },
    ]

    for template_data in templates:
        EmailTemplate.objects.get_or_create(
            name=template_data['name'],
            defaults={
                'subject_template': template_data['subject_template'],
                'description': template_data['description'],
            }
        )


def reverse_populate_email_templates(apps, schema_editor):
    """Remove all EmailTemplate records created by this migration."""
    EmailTemplate = apps.get_model('api', 'EmailTemplate')
    template_names = [
        'publish_reminder',
        'ownership_added',
        'ownership_removed',
        'registered_notice',
        'new_user_review',
        'user_approved',
        'user_rejected',
        'pending_users_review',
        'dandiset_unembargoed',
        'dandiset_unembargo_failed',
    ]
    EmailTemplate.objects.filter(name__in=template_names).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0030_emailtemplate_sentemail_remove_publish_reminder'),
    ]

    operations = [
        migrations.RunPython(
            populate_email_templates,
            reverse_populate_email_templates,
        ),
    ]
