# Generated by Django 5.2.7 on 2026-03-25 14:12
from __future__ import annotations

from django.db import migrations, models


def populate_asset_count(apps, schema_editor):
    Asset = apps.get_model('api.Asset')
    ApplicationStats = apps.get_model('api.ApplicationStats')

    asset_count = Asset.objects.filter(versions__isnull=False).distinct().count()

    ApplicationStats.objects.update(asset_count=asset_count)


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0030_alter_asset_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstats',
            name='asset_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.RunPython(code=populate_asset_count, reverse_code=migrations.RunPython.noop),
    ]
