# Generated by Django 5.2.7 on 2026-02-26 00:00
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0030_alter_asset_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(
                choices=[('Pending', 'Pending'), ('Valid', 'Valid'), ('Invalid', 'Invalid')],
                default='Pending',
                max_length=10,
            ),
        ),
    ]
