# Generated by Django 5.2.7 on 2026-04-21 21:39

from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0031_dandiset_embargo_end_date'),
        ('zarr', '0005_remove_zarrarchive_embargoed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='embargoed',
        ),
        migrations.AddField(
            model_name='upload',
            name='zarr',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='uploads',
                to='zarr.zarrarchive',
            ),
        ),
        migrations.AlterField(
            model_name='upload',
            name='dandiset',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='uploads',
                to='api.dandiset',
            ),
        ),
        migrations.AddConstraint(
            model_name='upload',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('dandiset__isnull', True), ('zarr__isnull', False)),
                    models.Q(('dandiset__isnull', False), ('zarr__isnull', True)),
                    _connector='OR',
                ),
                name='dandiset-zarr-xor',
            ),
        ),
    ]
