# Generated by Django 4.0.6 on 2022-08-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0032_embargoedzarrarchive_checksum_zarrarchive_checksum_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='embargoedzarrarchive',
            name='unique-embargo-dandiset-name',
        ),
        migrations.RemoveConstraint(
            model_name='embargoedzarrarchive',
            name='consistent-embargo-checksum-status',
        ),
        migrations.RemoveConstraint(
            model_name='zarrarchive',
            name='unique-dandiset-name',
        ),
        migrations.RemoveConstraint(
            model_name='zarrarchive',
            name='consistent-checksum-status',
        ),
        migrations.AddConstraint(
            model_name='embargoedzarrarchive',
            constraint=models.UniqueConstraint(
                fields=('dandiset', 'name'), name='api-embargoedzarrarchive-unique-name'
            ),
        ),
        migrations.AddConstraint(
            model_name='embargoedzarrarchive',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('checksum__isnull', True), ('status__in', ['Pending', 'Ingesting'])),
                    models.Q(('checksum__isnull', False), ('status', 'Complete')),
                    _connector='OR',
                ),
                name='api-embargoedzarrarchive-consistent-checksum-status',
            ),
        ),
        migrations.AddConstraint(
            model_name='zarrarchive',
            constraint=models.UniqueConstraint(
                fields=('dandiset', 'name'), name='api-zarrarchive-unique-name'
            ),
        ),
        migrations.AddConstraint(
            model_name='zarrarchive',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('checksum__isnull', True), ('status__in', ['Pending', 'Ingesting'])),
                    models.Q(('checksum__isnull', False), ('status', 'Complete')),
                    _connector='OR',
                ),
                name='api-zarrarchive-consistent-checksum-status',
            ),
        ),
    ]
