# Generated by Django 5.2.7 on 2026-04-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_add_doi_state_concept_doi_dataciteevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dandiset',
            name='concept_doi',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='doi_state',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('registered', 'Registered'), ('findable', 'Findable'), ('pending', 'Pending'), ('failed', 'Failed')], default=None, max_length=20, null=True),
        ),
    ]
