# Generated by Django 5.2.13 on 2026-09-11 19:47
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0032_version_release_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrecord',
            name='record_type',
            field=models.CharField(
                choices=[
                    ('create_dandiset', 'create_dandiset'),
                    ('change_owners', 'change_owners'),
                    ('update_metadata', 'update_metadata'),
                    ('add_asset', 'add_asset'),
                    ('update_asset', 'update_asset'),
                    ('remove_asset', 'remove_asset'),
                    ('bulk_remove_assets', 'bulk_remove_assets'),
                    ('create_zarr', 'create_zarr'),
                    ('upload_zarr_chunks', 'upload_zarr_chunks'),
                    ('delete_zarr_chunks', 'delete_zarr_chunks'),
                    ('finalize_zarr', 'finalize_zarr'),
                    ('unembargo_dandiset', 'unembargo_dandiset'),
                    ('publish_dandiset', 'publish_dandiset'),
                    ('delete_dandiset', 'delete_dandiset'),
                ],
                max_length=32,
            ),
        ),
    ]
