# Generated by Django 5.2.13 on 2026-08-11 15:52

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0032_version_release_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='embargoed',
        ),
    ]
