# Generated by Django 5.2.7 on 2026-04-28 14:06
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0032_remove_upload_embargoed_upload_zarr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dandiset',
            name='concept_doi',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='doi_state',
            field=models.CharField(
                blank=True,
                choices=[
                    ('draft', 'Draft'),
                    ('findable', 'Findable'),
                    ('pending', 'Pending'),
                    ('failed', 'Failed'),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
