# Generated by Django 4.1 on 2022-08-29 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0033_remove_embargoedzarrarchive_unique-embargo-dandiset-name_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='embargoedzarrarchive',
                    name='dandiset',
                ),
                migrations.RemoveField(
                    model_name='embargoedzarruploadfile',
                    name='zarr_archive',
                ),
                migrations.RemoveField(
                    model_name='zarrarchive',
                    name='dandiset',
                ),
                migrations.RemoveField(
                    model_name='zarruploadfile',
                    name='zarr_archive',
                ),
            ]
        )
    ]
