# Generated by Django 4.1 on 2022-08-29 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0034_remove_embargoedzarrarchive_dandiset_and_more'),
        ('zarr', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='asset',
                    name='zarr',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='assets',
                        to='zarr.zarrarchive',
                    ),
                ),
                migrations.DeleteModel(
                    name='EmbargoedZarrArchive',
                ),
                migrations.DeleteModel(
                    name='EmbargoedZarrUploadFile',
                ),
                migrations.DeleteModel(
                    name='ZarrArchive',
                ),
                migrations.DeleteModel(
                    name='ZarrUploadFile',
                ),
            ]
        )
    ]
