# Generated by Django 4.1 on 2022-09-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0036_dandisetuserobjectpermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Validating', 'Validating'),
                    ('Valid', 'Valid'),
                    ('Invalid', 'Invalid'),
                    ('Publishing', 'Publishing'),
                    ('Published', 'Published'),
                ],
                default='Pending',
                max_length=10,
            ),
        ),
    ]
