# Generated by Django 4.1 on 2022-09-10 16:57

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_dandisetuserobjectpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPath',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('path', models.CharField(max_length=512)),
                ('aggregate_files', models.PositiveBigIntegerField(default=0)),
                ('aggregate_size', models.PositiveBigIntegerField(default=0)),
                (
                    'asset',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='leaf_paths',
                        to='api.asset',
                    ),
                ),
                (
                    'version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='asset_paths',
                        to='api.version',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AssetPathRelation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('depth', models.PositiveIntegerField()),
                (
                    'child',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='parent_links',
                        to='api.assetpath',
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='child_links',
                        to='api.assetpath',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='assetpathrelation',
            constraint=models.UniqueConstraint(
                fields=('parent', 'child'), name='unique-relationship'
            ),
        ),
        migrations.AddConstraint(
            model_name='assetpath',
            constraint=models.CheckConstraint(
                check=models.Q(('path__endswith', '/'), _negated=True), name='consistent-slash'
            ),
        ),
        migrations.AddConstraint(
            model_name='assetpath',
            constraint=models.UniqueConstraint(
                fields=('asset', 'version'), name='unique-asset-version'
            ),
        ),
        migrations.AddConstraint(
            model_name='assetpath',
            constraint=models.UniqueConstraint(
                fields=('version', 'path'), name='unique-version-path'
            ),
        ),
    ]
