# Generated by Django 4.1.1 on 2022-10-04 19:21

from django.db import migrations, models
import django.db.models.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_dandisetuserobjectpermission_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('path', django.db.models.fields.json.KeyTextTransform('path', 'metadata'))
                ),
                name='asset_metadata_path_matches_path',
            ),
        ),
    ]
