# Generated by Django 4.1.1 on 2022-09-13 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_assetpath_assetpathrelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='path',
            field=models.CharField(
                max_length=512,
                validators=[
                    django.core.validators.RegexValidator(
                        '^([A-z0-9()\\s+~_-]+\\/)*([A-z0-9()\\s+~_-]+\\.?)+$'
                    )
                ],
            ),
        ),
    ]
