# Generated by Django 4.1.1 on 2022-10-04 21:33

from django.db import migrations, models

import dandiapi.api.models.asset


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_assetpath_assetpathrelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='path',
            field=models.CharField(
                max_length=512, validators=[dandiapi.api.models.asset.Asset.validate_path]
            ),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('path__regex', '^([A-z0-9(),&\\s#+~_-]?\\/?\\.?[A-z0-9(),&\\s#+~_-])+$')
                ),
                name='asset_path_regex',
            ),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(
                check=models.Q(('path__startswith', '/'), _negated=True),
                name='asset_path_no_leading_slash',
            ),
        ),
    ]
