# Generated by Django 4.1.1 on 2023-02-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0039_assetpath_consistent-leaf-paths'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetpath',
            name='consistent-slash',
        ),
        migrations.AddConstraint(
            model_name='assetpath',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('path__endswith', '/'), ('path__startswith', '/'), _connector='OR'),
                    _negated=True,
                ),
                name='consistent-slash',
            ),
        ),
    ]
