# Generated by Django 4.1.1 on 2022-11-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_assetpath_consistent-leaf-paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetblob',
            name='embargoed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upload',
            name='embargoed',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveConstraint(
            model_name='assetblob',
            name='unique-etag-size',
        ),
    ]
