# Generated by Django 4.1.4 on 2023-04-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0040_remove_assetpath_consistent-slash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetblob',
            name='download_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='embargoedassetblob',
            name='download_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
