# Generated by Django 4.1.7 on 2023-05-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0041_assetblob_download_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(
                fields=('dandiset', 'version'), name='api_version_unique_dandiset_version'
            ),
        ),
    ]
