# Generated by Django 4.1.1 on 2023-06-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0042_asset_remove_computed_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ('published', False),
                        models.Q(
                            (
                                'metadata__has_any_keys',
                                [
                                    'id',
                                    'path',
                                    'identifier',
                                    'contentUrl',
                                    'contentSize',
                                    'digest',
                                    'datePublished',
                                    'publishedBy',
                                ],
                            ),
                            _negated=True,
                        ),
                    ),
                    models.Q(
                        ('published', True),
                        (
                            'metadata__has_keys',
                            [
                                'id',
                                'path',
                                'identifier',
                                'contentUrl',
                                'contentSize',
                                'digest',
                                'datePublished',
                                'publishedBy',
                            ],
                        ),
                    ),
                    _connector='OR',
                ),
                name='asset_metadata_no_computed_keys_or_published',
            ),
        ),
    ]
