# Generated by Django 3.0.5 on 2020-04-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(model_name='nwbfile', name='size', field=models.BigIntegerField(),),
    ]
