# Generated by Django 3.0.8 on 2020-07-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'get_latest_by': 'created', 'ordering': ['dandiset', '-version']},
        ),
        migrations.AddField(
            model_name='version',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
