# Generated by Django 3.0.5 on 2020-04-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_auto_20200407_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dandiset', name='dandi_id', field=models.CharField(max_length=16),
        ),
    ]
