# Generated by Django 3.0.8 on 2020-07-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_asset_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
