# Generated by Django 3.0.5 on 2020-05-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_auto_20200407_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nwbfile',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nwb_files', to='publish.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='dandiset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='publish.Dandiset'),
        ),
    ]
