# Generated by Django 3.0.5 on 2020-05-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_auto_20200512_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dandiset',
            name='version',
            field=models.CharField(max_length=13),
        ),
    ]
