name: Release

on:
  push:
    branches:
      - master

# TODO: enable when we switch to GITHUB_TOKEN
# permissions:
#   contents: write

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # fetch history for all branches and tags
          token: ${{ secrets.GH_TOKEN }}  # TODO: switch to GITHUB_TOKEN

      - name: Download latest auto
        run: |
          auto_download_url="$(curl -fsSL https://api.github.com/repos/intuit/auto/releases/latest | jq -r '.assets[] | select(.name == "auto-linux.gz") | .browser_download_url')"
          wget -O- "$auto_download_url" | gunzip > ~/auto
          chmod a+x ~/auto

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # TODO: switch to GITHUB_TOKEN
        run: |
          ~/auto shipit --message="auto shipit - CHANGELOG.md etc"
