FROM node:20

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package.json yarn.lock ./
RUN yarn install --production=false

# Copy the rest of your application's code
COPY . .

# Expose the port the app runs on
EXPOSE 8085

# Start the application
CMD ["yarn", "run", "dev"]

