# Generated by Django 5.2.13 on 2026-09-19 23:01

from __future__ import annotations

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ('search', '0002_denormalize_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyTerm',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('curie', models.CharField(max_length=64, unique=True)),
                ('ontology', models.CharField(max_length=16)),
                ('iri', models.CharField(max_length=512)),
                ('label', models.CharField(max_length=512)),
                (
                    'names',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=512),
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                'indexes': [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=['names'], name='ontologyterm_names_gin'
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            django.db.models.functions.text.Upper('label'),
                            name='gin_trgm_ops',
                        ),
                        name='ontologyterm_label_trgm',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='OntologyClosure',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'ancestor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='descendant_links',
                        to='search.ontologyterm',
                    ),
                ),
                (
                    'descendant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ancestor_links',
                        to='search.ontologyterm',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('ancestor', 'descendant'),
                        name='unique_ontology_closure_pair',
                    )
                ],
            },
        ),
    ]
